### ISSUE TITLE
Quality button on video player

### ISSUE THREAD

**Issue by SilverEyesJP** [DevEkode/osu-replayViewer-web#23]
Some players like me don't have an good internet connection or a good pc to watch it on the actual "high quality" the player has, so would be nice if we could choose our preferred quality to watch online... https://i.imgur.com/1HZhMeR.png 
Every time i want watch a video in this website i have to download the video...
Btw keep the good work! <3

**Comment by codevirtuel** [comment]
Indeed, It was the reason why YouTube was my first option (but quickly abandoned because of copyrights)
But with my current system, If I add another video quality (like 480p), replay processing will be a lot longer.
Maybe someday, I'll create (or use) a video processing service to do that.

So, planned but hard to do now.
Also, thx for your support as always ❤️

**Comment by DevEkode** [comment]
Added in last little release
