### ISSUE TITLE
Skin issue

### ISSUE THREAD

**Issue by artic-02** [DevEkode/osu-replayViewer-web#74]
A skin was uploaded to the site, but it won't show up during the replay

**Comment by SpeckyYT** [comment]
artic, you have to do the following for making the skin work:
1) Log-in to the website
2) Click on "Profile"
3) When on profile, click "Edit Profile"
4) Select your custom skin

**Comment by Nintendero65XD** [comment]
My skin does not work but I have uploaded it where it corresponds and I have pressed the button that is just above and then I raised my replay, when I finished I was very excited because I always recorded my replays at 25-30 fps and now they were at 60 fps yay! but my skin did not appear, I was also impressed by the good website that I created Ekode but still I can not find a way to make my skin work

**Comment by DevEkode** [comment]
After some research the issue seem to be linked to the web server. Because the website is hosted on a limited access host. I cannot make the change my self. I've opened a ticket on my web host panel...

**Comment by Nintendero65XD** [comment]
> After some research the issue seem to be linked to the web server. Because the website is hosted on a limited access host. I cannot make the change my self. I've opened a ticket on my web host panel...

what does that mean?

**Comment by DevEkode** [comment]
> what does that mean?

It mean that I cannot access the file php.ini with my current plan on my webhost.
So only my webhost can do the change (If they want to do it)
